/*
go-sfgen generates constants from struct fields.

Below is a list of flags that can be used with the //go:generate directive.

Usage:

	go-sfgen --struct [struct_name] [flags]

Flags are:

	-dry-run
		If true, no output file will be written to, but instead results will be written to stdout
	-export
		If true, the generated constants will be exported
	-gen value
		accepts all the top level flags in a string, allowing multiple generate commands to be specified
	-include-struct-name
		If true, the generated constants will be prefixed with the source struct name
	-include-unexported-fields
		If true, the generated constants will include fields that are not exported on the struct
	-iter
		if true, an All() method will be generated for the type, which returns an array of all the values generated
	-out-dir string
		The directory in which to place the generated file. Defaults to the current directory (default ".")
	-out-file string
		The file to write generated output to. Defaults to [--struct]_[prefix]_generated.go
	-out-pkg string
		The package the generated code should belong to. Defaults to the package containing the go:generate directive
	-package string
		The name of the package in which the source struct resides.
	-prefix value
		A value to prepend to the generated const names. Defaults to [tag]Field
	-src-dir string
		The directory containing the --struct. Defaults to the current directory (default ".")
	-struct string
		The struct to use as the source for code generation. REQUIRED
	-style string
		Specifies the style of constants desired. Valid options are: alias, typed, generic
	-tag string
		If provided, the provided tag will be parsed for each field on the --struct.
		If the tag is missing, the struct field's name is used.
		Otherwise, the first attribute in the tag is used as the name'
	-tag-regex string
		This flag requires the --tag flag be provided as well.
		The provided regex will be tested on the specified tag contents for each field.
		The first capture group will be used as the value for the generated constant.
		If the regex does not match the tag contents, the struct field's' name will be used instead.
	-tests
		If true, source code in tests will be included. This flag will often need to be used along with the --package flag.
*/
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"go/types"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"sync"
	"unicode"

	"github.com/fatih/structtag"
)

var flagOptions []FlagOptions

func main() {
	flagOptions = parseOptions()
	err := os.Setenv("GODEBUG", "gotypesalias=1")
	if err != nil {
		log.Fatalf("failed to set GODEBUG variable")
	}
	defer func() {
		_ = os.Unsetenv("GODEBUG")
	}()

	var (
		outputFileGroups = make(map[string][]FlagOptions)
		packagesToLoad   = make([]packageToLoad, 0, len(flagOptions))
	)

	for _, fOpt := range flagOptions {
		absSrcDir, err := filepath.Abs(fOpt.SourceStructDir)
		if err != nil {
			log.Fatalf("failed to parse source dir: %s", fOpt.SourceStructDir)
		}
		pkgToLoad := packageToLoad{Dir: absSrcDir, IncludeTests: fOpt.IncludeTests, PackageName: fOpt.PackageName}
		packagesToLoad = append(packagesToLoad, pkgToLoad)
		fOpt.SourceStructDir = absSrcDir

		if fOpt.OutputFile == "" {
			fOpt.OutputFile = fmt.Sprintf("%s_%s_generated.go", strings.ToLower(fOpt.SourceStruct), strings.ToLower(calculateBaseName(fOpt)))
		}

		absOutDir, err := filepath.Abs(fOpt.OutputDir)
		if err != nil {
			log.Fatalf("failed to get absolute path to out file %q: %v", fOpt.OutputFile, err)
		}

		absOut := filepath.Join(absOutDir, fOpt.OutputFile)
		fOpt.OutputDir = absOutDir
		fOpt.OutputFile = absOut
		currentOpts := outputFileGroups[absOut]
		if len(currentOpts) > 0 && currentOpts[0].OutputPackage != fOpt.OutputPackage {
			log.Fatalf("invalid package values provided. Cannot use both %q and %q package values within output file %q",
				currentOpts[0].OutputFile, fOpt.OutputPackage, fOpt.OutputFile)
		}

		fOpt.packagesToLoad = pkgToLoad
		outputFileGroups[absOut] = append(outputFileGroups[absOut], fOpt)
	}

	loadPackageScopes(packagesToLoad)

	// var wg sync.WaitGroup
	for _, group := range outputFileGroups {
		// wg.Add(1)
		// go func(group []FlagOptions) {
		// 	defer wg.Done()
		generateCodeForFileGroup(group)
		// }(group)
	}

	// wg.Wait()
}

func generateCodeForFileGroup(flagOptions []FlagOptions) {
	if len(flagOptions) == 0 {
		return
	}

	var (
		err      error
		outPkg   = flagOptions[0].OutputPackage
		outFile  = flagOptions[0].OutputFile
		outDir   = flagOptions[0].OutputDir
		dryRun   = flagOptions[0].DryRun
		imports  = make([][]string, len(flagOptions))
		contents = make([][]byte, len(flagOptions))
	)

	for i, fOpt := range flagOptions {
		contents[i], imports[i], err = parsePackage(fOpt)
		if err != nil {
			log.Fatalf("failed to parse struct: %v", err)
		}
	}

	buf := new(bytes.Buffer)
	buf.WriteString("// Code generated by github.com/rad12000/go-sfgen; DO NOT EDIT.\n\n")
	fmt.Fprintf(buf, "// Source %s.%s:%s\n\n",
		os.Getenv("GOPACKAGE"), os.Getenv("GOFILE"), os.Getenv("GOLINE"))
	fmt.Fprintf(buf, "package %s\n", outPkg)
	seenImport := make(map[string]struct{})
	hasWrittenImportHeader := false
	for _, imports := range imports {
	InnerLoop:
		for _, imp := range imports {
			if _, ok := seenImport[imp]; ok {
				continue InnerLoop
			}

			seenImport[imp] = struct{}{}
			if !hasWrittenImportHeader {
				buf.WriteString("\nimport (\n")
				hasWrittenImportHeader = true
			}

			buf.WriteByte('"')
			buf.WriteString(imp)
			buf.WriteByte('"')
			buf.WriteByte('\n')
		}
	}
	if hasWrittenImportHeader {
		buf.WriteString(")\n")
	}

	for _, c := range contents {
		buf.Write(c)
		buf.WriteByte('\n')
	}

	if dryRun {
		printDryRun(buf.Bytes())
		return
	}

	if _, err = os.Stat(outFile); err != nil {
		err = os.MkdirAll(outDir, 0o755)
	}

	if err != nil {
		log.Fatalf("%v", err)
	}

	file, err := os.OpenFile(outFile, os.O_CREATE|os.O_TRUNC|os.O_WRONLY, 0o644)
	if err != nil {
		log.Fatalf("failed to open file at %s: %v", outFile, err)
	}
	defer func(file *os.File) {
		_ = file.Close()
	}(file)
	_ = file.Truncate(0)

	unformatted := buf.Bytes()
	out, err := format.Source(unformatted)
	if err != nil {
		_, _ = os.Stdout.Write(unformatted)
		panic(fmt.Sprintf("failed to format output '%v'", err))
	}

	if _, err = file.Write(out); err != nil {
		log.Fatalf("failed to write to out file %s: %v", outFile, err)
	}
}

func printDryRun(b []byte) {
	out, err := format.Source(b)
	if err != nil {
		panic(fmt.Sprintf("failed to format output '%v': %s", err, b))
	}

	if _, err = os.Stdout.Write(out); err != nil {
		panic(fmt.Sprintf("failed to write to stdout: %v", err))
	}
}

func parseOptions() []FlagOptions {
	var (
		commands     = NewMultiFlagOptions()
		topLevelOpts FlagOptions
	)

	flag.Var(&commands, "gen", "accepts all the top level flags in a string, allowing multiple generate commands to be specified")
	topLevelOpts.RegisterFlags(flag.CommandLine)
	flag.Parse()

	var (
		visitedGen    bool
		visitedNonGen bool
	)

	flag.Visit(func(f *flag.Flag) {
		if f.Name == "gen" {
			visitedGen = true
		} else {
			visitedNonGen = true
		}
	})

	if visitedGen && visitedNonGen {
		log.Fatalf("if --gen flags are used, only --gen flags may be provided")
	}

	if visitedGen {
		return commands.Slice()
	}

	if err := topLevelOpts.Validate(); err != nil {
		log.Fatal(err.Error())
	}

	return []FlagOptions{topLevelOpts}
}

func parsePackage(f FlagOptions) (code []byte, imports []string, err error) {
	if f.Iter && f.Style == StyleAlias {
		log.Fatalf("Invalid style %s: only %s and %s styles may be used with the --iter flag", f.Style, StyleGeneric, StyleTyped)
	}

	structType, s, err := loadStruct(f.packagesToLoad, f.SourceStruct)
	if err != nil {
		return nil, nil, err
	}
	structPackage := structType.String()[:strings.LastIndexByte(structType.String(), '.')]

	var (
		outBuf         bytes.Buffer
		constBuf       bytes.Buffer
		closeConstants = func() {
			constBuf.WriteByte(')')
		}
	)

	baseName := calculateBaseName(f)
	firstChar := strings.ToLower(baseName[:1])

	if f.Style != "" {
		fmt.Fprintf(&outBuf, "// %s is a strong type generated from %s. Its type is used for all of its related generated constants.\n", baseName, f.SourceStruct)
	}

	switch f.Style {
	case StyleAlias:
		fmt.Fprintf(&outBuf, "type %s = string\n", baseName)
	case StyleTyped:
		fmt.Fprintf(&outBuf, "type %s string\n", baseName)
		outBuf.WriteString("// String implements the [fmt.Stringer] interface\n")
		fmt.Fprintf(&outBuf, "func (%s %s) String() string { return (string)(%s) }\n", firstChar, baseName, firstChar)
	case StyleGeneric:
		fmt.Fprintf(&outBuf, "type %s[T any] string\n", baseName)
		outBuf.WriteString("// String implements the [fmt.Stringer] interface\n")
		fmt.Fprintf(&outBuf, "func (%s %s[T]) String() string { return (string)(%s) }\n", firstChar, baseName, firstChar)
	}

	parsedStruct, err := parseStructFields(f, structPackage, baseName, s)
	if err != nil {
		return nil, nil, err
	}
	fields := parsedStruct.Fields

	if len(fields) == 0 {
		closeConstants()
	}

	var fieldNames []string
	for i, field := range fields {
		fmt.Println("looking at field", field.FieldName)
		if f.Style == StyleGeneric {
			imports = append(imports, field.Imports()...)
		}

		if constBuf.Len() == 0 {
			constBuf.WriteByte('\n')
			fmt.Fprintf(&constBuf, "// Constants generated from [%s] struct field\n", f.SourceStruct)
			constBuf.WriteString("const (")
		} else {
			constBuf.WriteByte('\n')
		}

		switch f.Style {
		case StyleAlias, StyleTyped:
			fmt.Fprintf(&constBuf, "%s %s = %q", field.ConstName, parsedStruct.BaseName, field.ConstValue)
		case StyleGeneric:
			fmt.Fprintf(&constBuf, "%s %s[%s] = %q", field.ConstName, parsedStruct.BaseName, field.TypeName(), field.ConstValue)
		default:
			fmt.Fprintf(&constBuf, "%s = %q", field.ConstName, field.ConstValue)
		}
		fieldNames = append(fieldNames, field.ConstValue)
		if i == len(fields)-1 {
			closeConstants()
		}
	}

	if f.Iter {
		fmt.Fprintf(&outBuf, "// All was generated from the [%s] struct. It returns an array of all [%s]'s associated constant values.\n", f.SourceStruct, baseName)

		var sb strings.Builder
		for _, n := range fieldNames {
			sb.WriteByte('\n')
			sb.WriteByte('"')
			sb.WriteString(n)
			sb.WriteByte('"')
			sb.WriteByte(',')
		}
		fieldNamesStr := sb.String()
		if f.Style == StyleGeneric {
			outBuf.WriteString(fmt.Sprintf("func (%s %s[T]) All() [%d]string { return [%d]string{%s} }\n", firstChar, baseName, len(fieldNames), len(fieldNames), fieldNamesStr))
		} else {
			fmt.Fprintf(&outBuf, "func (%s %s) All() [%d]string { return [%d]string{%s} }\n", firstChar, baseName, len(fieldNames), len(fieldNames), fieldNamesStr)
		}
	}

	if _, err = constBuf.WriteTo(&outBuf); err != nil {
		log.Fatalf("failed to write full contents in memory: %v", err)
	}

	return outBuf.Bytes(), imports, nil
}

func fieldIsEmbeddedStruct(f *types.Var) (*types.Struct, bool) {
	if !f.Embedded() {
		return nil, false
	}

	t := f.Type()
	for {
		switch v := t.(type) {
		case *types.Pointer:
			t = t.Underlying()
		case *types.Named:
			t = t.Underlying()
		case *types.Struct:
			return v, true
		default:
			return nil, false
		}
	}
}

var seen = make(map[string]struct{})

type parseStructFieldsResult struct {
	BaseName string
	Fields   []ParsedField
}

func parseStructFields(f FlagOptions, structPackage, baseName string, s *types.Struct) (parseStructFieldsResult, error) {
	if _, ok := seen[s.String()]; ok {
		return parseStructFieldsResult{}, nil
	}
	seen[s.String()] = struct{}{}

	bName := []rune(baseName)
	if f.Export {
		bName[0] = unicode.ToUpper(bName[0])
	} else {
		bName[0] = unicode.ToLower(bName[0])
	}
	baseName = string(bName)

	var (
		topLevelFields = make(map[string]struct{})
		fields         []ParsedField
		embeddedFields []ParsedField
	)
	for i := 0; i < s.NumFields(); i++ {
		field := s.Field(i)
		if !f.IncludeUnexportedFields && !field.Exported() {
			continue
		}

		tag := s.Tag(i)
		parseFieldResult, err := parseTopLevelField(structPackage, field, tag, baseName, f)
		if err != nil {
			return parseStructFieldsResult{}, fmt.Errorf("failed to parse field with name %s: %w", field.Name(), err)
		}

		if parseFieldResult.ConstValue == "-" { // Handle the case that the field is ignored
			continue
		}

		if structType, ok := fieldIsEmbeddedStruct(field); ok {
			embFields, err := parseStructFields(f, structPackage, baseName, structType)
			if err != nil {
				return parseStructFieldsResult{}, err
			}

			embeddedFields = append(embeddedFields, embFields.Fields...)
			continue
		}

		fields = append(fields, parseFieldResult)
		topLevelFields[parseFieldResult.ConstName] = struct{}{}
	}

	for _, field := range embeddedFields {
		_, ok := topLevelFields[field.ConstName]
		if ok {
			continue
		}
		fields = append(fields, field)
	}

	return parseStructFieldsResult{
		BaseName: baseName,
		Fields:   fields,
	}, nil
}

type ParsedField struct {
	StructField

	// ConstName is the name of the constant to be generated for this field.
	// For example, if the source struct is "Config", the field is "Timeout", and the prefix is "Field", this will be "ConfigFieldTimeout" or "FieldTimeout" depending on whether the --include-struct-name flag is used.
	ConstName string

	// ConstValue is the value of the constant to be generated for this field.
	// By default, this is the field's name, but it can be overridden by struct tags.
	ConstValue string
}

func parseTopLevelField(structPackage string, field *types.Var, tag, baseName string, f FlagOptions) (ParsedField, error) {
	tags, err := structtag.Parse(tag)
	if err != nil {
		return ParsedField{}, fmt.Errorf("failed to parse struct tags for field %s: %w", field.Name(), err)
	}

	structField := parseStructField(structPackage, field)
	if sfgenTag, ok := sfgenTagName(f.Tag, tags); ok {
		return ParsedField{
			ConstName:   baseName + field.Name(),
			ConstValue:  sfgenTag,
			StructField: structField,
		}, nil
	}

	tagNameValue := field.Name()
	if f.Tag != "" {
		nameFromTag, err := tags.Get(f.Tag)
		if err == nil && len(nameFromTag.Value()) > 0 && f.TagNameRegex != "" {
			re, err := regexp.Compile(f.TagNameRegex)
			if err != nil {
				return ParsedField{}, fmt.Errorf("failed to compile regex expression %q: %w", f.TagNameRegex, err)
			}

			if matches := re.FindStringSubmatch(nameFromTag.Value()); len(matches) >= 2 {
				tagNameValue = matches[1]
			}
		}

		if err == nil && len(nameFromTag.Name) > 0 && f.TagNameRegex == "" {
			tagNameValue = nameFromTag.Name
		}
	}

	return ParsedField{
		ConstName:   baseName + field.Name(),
		ConstValue:  tagNameValue,
		StructField: structField,
	}, nil
}

func parseStructField(structPackage string, field *types.Var) StructField {
	fieldType := parseTypeName(structPackage, field.Type())
	return StructField{
		Embedded:  field.Embedded(),
		Exported:  field.Exported(),
		FieldName: field.Name(),
		FieldType: fieldType,
	}
}

func sfgenTagName(targetTagName string, tags *structtag.Tags) (string, bool) {
	sfgenTag, err := tags.Get("sfgen")
	if err != nil {
		return "", false
	}

	tagValue := sfgenTag.Value()
	if tagValue == "" {
		return "", false
	}

	tagParts := strings.SplitN(strings.TrimSpace(tagValue), ",", 2)
	tagName := tagParts[0] // We are guaranteed at least a slice with len(1)
	if len(tagParts) == 1 {
		return tagName, tagName != ""
	}

	// From here on we know that tagParts length is 2
	tagSpecificValues := strings.Split(tagParts[1], " ")
	for _, tagSpecificVal := range tagSpecificValues {
		tagSpecificVal = strings.TrimSpace(tagSpecificVal)
		if tagSpecificVal == "" {
			continue
		}

		tagValParts := strings.SplitN(tagSpecificVal, ":", 2)
		if len(tagValParts) != 2 || tagValParts[0] != targetTagName {
			continue
		}

		if tagValParts[1] != "" {
			tagName = tagValParts[1]
			break
		}
	}

	return tagName, tagName != ""
}

func calculateBaseName(f FlagOptions) string {
	var (
		tagName string
		prefix  string
	)

	if f.UseStructName || f.Export {
		tagName = strings.ToUpper(f.Tag)
	} else {
		tagName = strings.ToLower(f.Tag)
	}

	if f.Prefix == nil {
		prefix = f.SourceStruct + tagName
		if !f.UseStructName {
			prefix = tagName
		}

		prefix += "Field"
	} else {
		prefix = *f.Prefix
	}

	properlyCasedName := []rune(prefix)
	if f.Export {
		properlyCasedName[0] = unicode.ToUpper(properlyCasedName[0])
	} else {
		properlyCasedName[0] = unicode.ToLower(properlyCasedName[0])
	}

	return string(properlyCasedName)
}

func loadStruct(source packageToLoad, structName string) (*types.Named, *types.Struct, error) {
	pkg, scope, ok := scopeForPackage(source)
	if !ok {
		var a []string
		for k := range packageNameToScopes {
			a = append(a, k)
		}
		return nil, nil, fmt.Errorf("failed to find package scope: %s, %+v", source, a)
	}

	// *types.TypeName is returned here
	foundObj := scope.Lookup(structName)
	if foundObj == nil {
		foundObj = scope.Lookup(strings.SplitN(structName, ".", 2)[1])
	}
	if foundObj == nil {
		return nil, nil, fmt.Errorf("type %s not found in package %s#%s", structName, pkg.Dir, pkg.Name)
	}

	n, ok := foundObj.Type().(*types.Named)
	if !ok {
		return nil, nil, fmt.Errorf("cannot use type %s, only named struct types are supported", structName)
	}

	s, ok := n.Underlying().(*types.Struct)
	if !ok {
		return nil, nil, fmt.Errorf("cannot use type %s, only named struct types are supported", structName)
	}

	return n, s, nil
}

func parseNamedType(structPackage string, u types.Type) (string, []string) {
	name := u.String()
	dotIndex := strings.LastIndexByte(name, '.')
	pkgPath := name
	if dotIndex >= 0 {
		pkgPath = name[:dotIndex]
	}

	if pkgPath == structPackage {
		return name[dotIndex+1:], nil
	}

	slashIndex := strings.LastIndexByte(name, '/')
	newName := name
	if slashIndex >= 0 {
		newName = name[slashIndex+1:]
	}

	if dotIndex >= 0 {
		return newName, []string{name[:dotIndex]}
	}

	return newName, nil
}

func parseTypeNameSignature(structPackage string, u *types.Signature) *FieldType {
	result := FuncSignature{
		Parameters:       make([]FuncParam, 0, u.Params().Len()),
		ReturnParameters: make([]FuncParam, 0, u.Results().Len()),
	}

	for i := 0; i < u.Params().Len(); i++ {
		param := u.Params().At(i)
		parsedType := parseTypeName(structPackage, param.Type())
		result.Parameters = append(result.Parameters, FuncParam{
			Name: param.Name(),
			Type: parsedType,
		})
	}

	for i := 0; i < u.Results().Len(); i++ {
		param := u.Results().At(i)
		parsedType := parseTypeName(structPackage, param.Type())
		result.ReturnParameters = append(result.Parameters, FuncParam{
			Name: param.Name(),
			Type: parsedType,
		})
	}

	typeNameAndImports := sync.OnceValues(func() (string, []string) {
		var (
			sb      strings.Builder
			imports []string
		)
		sb.WriteString("func (")

		for i, param := range result.Parameters {
			imports = append(imports, param.Type.Imports()...)
			if i > 0 && i < len(result.Parameters) {
				sb.WriteByte(',')
			}
			sb.WriteString(param.Name)
			sb.WriteByte(' ')
			sb.WriteString(param.Type.TypeName())
		}

		sb.WriteByte(')')

		if len(result.ReturnParameters) > 1 {
			sb.WriteByte('(')
		}

		for i, param := range result.ReturnParameters {
			imports = append(imports, param.Type.Imports()...)
			if i > 0 && i < len(result.ReturnParameters) {
				sb.WriteByte(',')
			}
			sb.WriteString(param.Type.TypeName())
		}

		if len(result.ReturnParameters) > 1 {
			sb.WriteByte(')')
		}

		return sb.String(), imports
	})

	return &FieldType{
		TypeName: func() string {
			typeName, _ := typeNameAndImports()
			return typeName
		},
		Imports: func() []string {
			_, imports := typeNameAndImports()
			return imports
		},
		IsFuncSignature: true,
		FuncSignature:   result,
	}
}
