// Code generated by github.com/rad12000/go-sfgen; DO NOT EDIT.

// Source gen.combined_flags.go:1

package gen

// CombinedStructJSONField is a type, generated from CombinedStruct
// Its type is used for all of its related generated constants.
type CombinedStructJSONField string

// String implements the [fmt.Stringer] interface.
func (c CombinedStructJSONField) String() string {
	return string(c)
}

// Constants generated from the fields defined on the [CombinedStruct] struct.
const (
	CombinedStructJSONFieldID       CombinedStructJSONField = "id"
	CombinedStructJSONFieldFullName CombinedStructJSONField = "full_name"
	CombinedStructJSONFieldIsActive CombinedStructJSONField = "is_active"
	CombinedStructJSONFieldScore    CombinedStructJSONField = "score"
)

// All was generated from [CombinedStruct]. It returns an array of [CombinedStructJSONField]'s constants.
func (c CombinedStructJSONField) All() []string {
	return []string{
		"id",
		"full_name",
		"is_active",
		"score",
	}
}
