// Code generated by github.com/rad12000/go-sfgen; DO NOT EDIT.

// Source gen.combined_flags.go:1

package gen

// CombinedStructJSONField is a strong type generated from CombinedStruct. Its type is used for all of its related generated constants.
type CombinedStructJSONField string

// String implements the [fmt.Stringer] interface
func (c CombinedStructJSONField) String() string { return (string)(c) }

// All was generated from the [CombinedStruct] struct. It returns an array of all [CombinedStructJSONField]'s associated constant values.
func (c CombinedStructJSONField) All() [4]string {
	return [4]string{
		"id",
		"full_name",
		"is_active",
		"score"}
}

// Constants generated from [CombinedStruct] struct field
const (
	CombinedStructJSONFieldID       CombinedStructJSONField = "id"
	CombinedStructJSONFieldFullName CombinedStructJSONField = "full_name"
	CombinedStructJSONFieldIsActive CombinedStructJSONField = "is_active"
	CombinedStructJSONFieldScore    CombinedStructJSONField = "score"
)
