// Code generated by github.com/rad12000/go-sfgen; DO NOT EDIT.

// Source gen.custom_prefix.go:1

package gen

// Constants generated from [CustomPrefixStruct] struct field
const (
	myCustomFoo = "Foo"
	myCustomBar = "Bar"
	myCustomBaz = "Baz"
)
