// Code generated by github.com/rad12000/go-sfgen; DO NOT EDIT.

// Source gen.custom_prefix_export.go:1

package gen

// Constants generated from [CustomPrefixExportStruct] struct field
const (
	MyCustomAlpha = "Alpha"
	MyCustomBeta  = "Beta"
	MyCustomGamma = "Gamma"
)
