// Code generated by github.com/rad12000/go-sfgen; DO NOT EDIT.

// Source gen.default.go:1

package gen

import (
	"time"
)

// field is a strong type generated from Simple. Its type is used for all of its related generated constants.
type field[T any] string

// String implements the [fmt.Stringer] interface
func (f field[T]) String() string { return (string)(f) }

// Constants generated from [Simple] struct field
const (
	fieldString  field[string]            = "String"
	fieldMap     field[map[string]Simple] = "Map"
	fieldSlice   field[[]Simple]          = "Slice"
	fieldChannel field[chan<- Simple]     = "Channel"
	fieldArray   field[[3]int]            = "Array"
	fieldGeneric field[Number[int]]       = "Generic"
	fieldAlias   field[StringAlias]       = "Alias"
	fieldImports field[time.Time]         = "Imports"
)
