// Code generated by github.com/rad12000/go-sfgen; DO NOT EDIT.

// Source gen.embedded_struct.go:1

package gen

// field is a type, generated from ChildStruct
// Its type is used for all of its related generated constants.
type field string

// String implements the [fmt.Stringer] interface.
func (f field) String() string {
	return string(f)
}

// Constants generated from the fields defined on the [.Struct.Name] struct.
const (
	fieldChildField  field = "ChildField"
	fieldSharedField field = "SharedField"
	fieldParentField field = "ParentField"
)
