// Code generated by github.com/rad12000/go-sfgen; DO NOT EDIT.

// Source gen.export_with_tag.go:1

package gen

// Constants generated from [ExportTagStruct] struct field
const (
	JSONFieldUserName  = "user_name"
	JSONFieldUserEmail = "user_email"
	JSONFieldUserAge   = "user_age"
)
