// Code generated by github.com/rad12000/go-sfgen; DO NOT EDIT.

// Source gen.export.go:1

package gen

// Constants generated from [ExportStruct] struct field
const (
	FieldUsername = "Username"
	FieldPassword = "Password"
	FieldToken    = "Token"
)
