// Code generated by github.com/rad12000/go-sfgen; DO NOT EDIT.

// Source gen.include_struct_name.go:1

package gen

// Constants generated from [StructNameStruct] struct field
const (
	structNameStructFieldID     = "ID"
	structNameStructFieldLabel  = "Label"
	structNameStructFieldStatus = "Status"
)
