// Code generated by github.com/rad12000/go-sfgen; DO NOT EDIT.

// Source gen.include_unexported.go:1

package gen

// Constants generated from [UnexportedStruct] struct field
const (
	fieldPublic   = "Public"
	fieldhidden   = "hidden"
	fieldsecret   = "secret"
	fieldVisible  = "Visible"
	fieldinternal = "internal"
)
