// Code generated by github.com/rad12000/go-sfgen; DO NOT EDIT.

// Source gen.include_struct_name_export.go:1

package gen

// Constants generated from the fields defined on the [.Struct.Name] struct.
const (
	StructNameExportStructFieldWidth  = "Width"
	StructNameExportStructFieldHeight = "Height"
	StructNameExportStructFieldDepth  = "Depth"
)
