// Code generated by github.com/rad12000/go-sfgen; DO NOT EDIT.

// Source gen.iter_typed.go:1

package gen

// field is a strong type generated from IterTypedStruct. Its type is used for all of its related generated constants.
type field string

// String implements the [fmt.Stringer] interface
func (f field) String() string { return (string)(f) }

// All was generated from the [IterTypedStruct] struct. It returns an array of all [field]'s associated constant values.
func (f field) All() [3]string {
	return [3]string{
		"One",
		"Two",
		"Three"}
}

// Constants generated from [IterTypedStruct] struct field
const (
	fieldOne   field = "One"
	fieldTwo   field = "Two"
	fieldThree field = "Three"
)
