// Code generated by github.com/rad12000/go-sfgen; DO NOT EDIT.

// Source gen.iter_generic.go:1

package gen

// field is a type, generated from IterGenericStruct
// Its type is used for all of its related generated constants.
type field[T any] string

// String implements the [fmt.Stringer] interface.
func (f field[T]) String() string {
	return string(f)
}

// Constants generated from the fields defined on the [IterGenericStruct] struct.
const (
	fieldName  field[string] = "Name"
	fieldCount field[int]    = "Count"
	fieldFlag  field[bool]   = "Flag"
)

// All was generated from [IterGenericStruct]. It returns an array of [field]'s constants.
func (f field[T]) All() []string {
	return []string{
		"Name",
		"Count",
		"Flag",
	}
}
