// Code generated by github.com/rad12000/go-sfgen; DO NOT EDIT.

// Source gen.iter_generic.go:1

package gen

// field is a strong type generated from IterGenericStruct. Its type is used for all of its related generated constants.
type field[T any] string

// String implements the [fmt.Stringer] interface
func (f field[T]) String() string { return (string)(f) }

// All was generated from the [IterGenericStruct] struct. It returns an array of all [field]'s associated constant values.
func (f field[T]) All() [3]string {
	return [3]string{
		"Name",
		"Count",
		"Flag"}
}

// Constants generated from [IterGenericStruct] struct field
const (
	fieldName  field[string] = "Name"
	fieldCount field[int]    = "Count"
	fieldFlag  field[bool]   = "Flag"
)
