// Code generated by github.com/rad12000/go-sfgen; DO NOT EDIT.

// Source gen.iter_typed.go:1

package gen

// field is a type, generated from IterTypedStruct
// Its type is used for all of its related generated constants.
type field string

// String implements the [fmt.Stringer] interface.
func (f field) String() string {
	return string(f)
}

// Constants generated from the fields defined on the [.Struct.Name] struct.
const (
	fieldOne   field = "One"
	fieldTwo   field = "Two"
	fieldThree field = "Three"
)

// All was generated from [IterTypedStruct]. It returns an array of [field]'s constants.
func (f field) All() []string {
	return []string{
		"One",
		"Two",
		"Three",
	}
}
