// Code generated by github.com/rad12000/go-sfgen; DO NOT EDIT.

// Source gen.no_style.go:1

package gen

// Constants generated from [NoStyleStruct] struct field
const (
	fieldHost = "Host"
	fieldPort = "Port"
	fieldTLS  = "TLS"
)
