// Code generated by github.com/rad12000/go-sfgen; DO NOT EDIT.

// Source gen.no_style.go:1

package gen

// Constants generated from the fields defined on the [NoStyleStruct] struct.
const (
	fieldHost = "Host"
	fieldPort = "Port"
	fieldTLS  = "TLS"
)
