// Code generated by github.com/rad12000/go-sfgen; DO NOT EDIT.

// Source gen.out_pkg.go:1

package custompkg

// Constants generated from [OutPkgStruct] struct field
const (
	fieldServer = "Server"
	fieldPort   = "Port"
)
