// Code generated by github.com/rad12000/go-sfgen; DO NOT EDIT.

// Source gen.out_pkg.go:1

package custompkg

// field is a type, generated from OutPkgStruct
// Its type is used for all of its related generated constants.
type field[T any] string

// String implements the [fmt.Stringer] interface.
func (f field) String() string {
	return string(f)
}

// Constants generated from the fields defined on the [.Struct.Name] struct.
const (
	fieldServer            field[string] = "Server"
	fieldPort              field[int]    = "Port"
	fieldExternalReference field[Foo]    = "ExternalReference"
)
