// Code generated by github.com/rad12000/go-sfgen; DO NOT EDIT.

// Source gen.sfgen_tag.go:1

package gen

// jsonField is a type, generated from SfgenTagStruct
// Its type is used for all of its related generated constants.
type jsonField string

// String implements the [fmt.Stringer] interface.
func (j jsonField) String() string {
	return string(j)
}

// Constants generated from the fields defined on the [SfgenTagStruct] struct.
const (
	jsonFieldNormal      jsonField = "normal_field"
	jsonFieldOverridden  jsonField = "custom_override"
	jsonFieldTagSpecific jsonField = "sfgen_json_val"
	jsonFieldPlain       jsonField = "Plain"
)
