// Code generated by github.com/rad12000/go-sfgen; DO NOT EDIT.

// Source gen.style_alias.go:1

package gen

// field is a type, generated from AliasStruct
// Its type is used for all of its related generated constants.
type field = string

// Constants generated from the fields defined on the [.Struct.Name] struct.
const (
	fieldFirstName field = "FirstName"
	fieldLastName  field = "LastName"
	fieldEmail     field = "Email"
)
