// Code generated by github.com/rad12000/go-sfgen; DO NOT EDIT.

// Source gen.style_typed.go:1

package gen

// field is a type, generated from TypedStruct
// Its type is used for all of its related generated constants.
type field string

// String implements the [fmt.Stringer] interface.
func (f field) String() string {
	return string(f)
}

// Constants generated from the fields defined on the [TypedStruct] struct.
const (
	fieldName    field = "Name"
	fieldAge     field = "Age"
	fieldActive  field = "Active"
	fieldBalance field = "Balance"
)
