// Code generated by github.com/rad12000/go-sfgen; DO NOT EDIT.

// Source gen.tag_db.go:1

package gen

// Constants generated from [TagDBStruct] struct field
const (
	dbFieldUserID    = "user_id"
	dbFieldUserName  = "user_name"
	dbFieldNoDBTag   = "NoDBTag"
	dbFieldCreatedAt = "created_at"
)
