// Code generated by github.com/rad12000/go-sfgen; DO NOT EDIT.

// Source gen.tag_json.go:1

package gen

// Constants generated from [TagJSONStruct] struct field
const (
	jsonFieldFirstName = "first_name"
	jsonFieldLastName  = "last_name"
	jsonFieldAge       = "age"
	jsonFieldNoTag     = "NoTag"
)
