// Code generated by github.com/rad12000/go-sfgen; DO NOT EDIT.

// Source gen.tag_regex.go:1

package gen

// Constants generated from [TagRegexStruct] struct field
const (
	dbFieldUserID   = "user_id"
	dbFieldUserName = "user_name"
	dbFieldNotes    = "Notes"
	dbFieldNoTag    = "NoTag"
)
