name: Bump version
on:
  push:
#    paths-ignore:
#      - '**/*README.md'
#      - '.github/**'
    branches:
      - main
jobs:
  version:
    permissions:
      contents: write
    name: Bump Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Test
        run: go test -v ./...

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          body: "# ${{ github.event.pull_request.title }}\n\n${{ github.event.pull_request.body }}"